--CREATE TABLE users(
                    -- id_user int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                     -- username varchar(30) UNIQUE,
                     -- password varchar(30)
--);


CREATE TABLE roles(
                      id_role int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      role varchar(20)
);

create table users (
                       id serial primary key,
                       name varchar(255),
                       role_id int REFERENCES roles(id_role)
);

CREATE TABLE rules(
                      id_rule int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      rule varchar(40)
);

CREATE TABLE items(
                      id_item int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      name varchar(30) UNIQUE,
                      price int
);

CREATE TABLE comments(
                         id_comment int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         comment varchar(300)
);

CREATE TABLE attaches(
                         id_attache int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         attache varchar(500)
);

CREATE TABLE states(
                       id_state int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       state varchar(30)
);

CREATE TABLE categories(
                           id_category int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           category varchar(40)
);


